// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "IntakeOutCommand.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

IntakeOutCommand::IntakeOutCommand(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::intakeSystem.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void IntakeOutCommand::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void IntakeOutCommand::Execute() {
	Robot::intakeSystem->Out();
}

// Make this return true when this Command no longer needs to run execute()
bool IntakeOutCommand::IsFinished() {
	frc::XboxController Xbox1(0);

	bool buttonvalue = Xbox1.GetRawButton(6);
	if(buttonvalue==true){
		return false;
	}
	else{
		return true;
	}
}

// Called once after isFinished returns true
void IntakeOutCommand::End() {
	Robot::intakeSystem->Stop();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void IntakeOutCommand::Interrupted() {

}
