// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/CompressorOffCommand.h"
#include "Commands/CompressorOnCommand.h"
#include "Commands/DrivingCommand.h"
#include "Commands/HangingCommand.h"
#include "Commands/IntakeCommand.h"
#include "Commands/IntakeInCommand.h"
#include "Commands/IntakeOutCommand.h"
#include "Commands/SolenoidCommand1.h"
#include "Commands/SolenoidCommand2.h"
#include "Commands/SolenoidCommand3.h"
#include "Commands/SolenoidCommand4.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {

    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	Xbox1.reset(new frc::XboxController(0));
    joystickButton12.reset(new frc::JoystickButton(Xbox1.get(), 4));
    joystickButton12->WhenReleased(new SolenoidCommand4());
    joystickButton11.reset(new frc::JoystickButton(Xbox1.get(), 3));
    joystickButton11->WhenReleased(new SolenoidCommand3());
    joystickButton10.reset(new frc::JoystickButton(Xbox1.get(), 2));
    joystickButton10->WhenReleased(new SolenoidCommand2());
    joystickButton9.reset(new frc::JoystickButton(Xbox1.get(), 1));
    joystickButton9->WhenReleased(new SolenoidCommand1());
    joystickButton8.reset(new frc::JoystickButton(Xbox1.get(), 7));
    joystickButton8->WhenPressed(new CompressorOffCommand());
    joystickButton7.reset(new frc::JoystickButton(Xbox1.get(), 8));
    joystickButton7->WhenPressed(new CompressorOnCommand());
    joystickButton4.reset(new frc::JoystickButton(Xbox1.get(), 6));
    joystickButton4->WhenPressed(new IntakeOutCommand());
    joystickButton3.reset(new frc::JoystickButton(Xbox1.get(), 5));
    joystickButton3->WhenPressed(new IntakeInCommand());

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("SolenoidCommand4", new SolenoidCommand4());
    frc::SmartDashboard::PutData("SolenoidCommand3", new SolenoidCommand3());
    frc::SmartDashboard::PutData("SolenoidCommand2", new SolenoidCommand2());
    frc::SmartDashboard::PutData("SolenoidCommand1", new SolenoidCommand1());
    frc::SmartDashboard::PutData("CompressorOffCommand", new CompressorOffCommand());
    frc::SmartDashboard::PutData("CompressorOnCommand", new CompressorOnCommand());
    frc::SmartDashboard::PutData("DrivingCommand", new DrivingCommand());
    frc::SmartDashboard::PutData("HangingCommand", new HangingCommand());
    frc::SmartDashboard::PutData("IntakeOutCommand", new IntakeOutCommand());
    frc::SmartDashboard::PutData("IntakeInCommand", new IntakeInCommand());
    frc::SmartDashboard::PutData("IntakeCommand", new IntakeCommand());
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

//    SolenoidButton9 = frc::JoystickButton(joystick1.get(), 9);
//    SolenoidButton10 = frc::JoystickButton(joystick1.get(), 10);
//    SolenoidButton11 = frc::JoystickButton(joystick1.get(), 11);
//    SolenoidButton12 = frc::JoystickButton(joystick1.get(), 12);




    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::XboxController> OI::getXbox1() {
   return Xbox1;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
