// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	std::shared_ptr<frc::XboxController> Xbox1;
	std::shared_ptr<frc::JoystickButton> joystickButton12;
	std::shared_ptr<frc::JoystickButton> joystickButton11;
	std::shared_ptr<frc::JoystickButton> joystickButton10;
	std::shared_ptr<frc::JoystickButton> joystickButton9;
	std::shared_ptr<frc::JoystickButton> joystickButton8;
	std::shared_ptr<frc::JoystickButton> joystickButton7;
	std::shared_ptr<frc::JoystickButton> joystickButton6;
	std::shared_ptr<frc::JoystickButton> joystickButton5;
	std::shared_ptr<frc::JoystickButton> joystickButton4;
	std::shared_ptr<frc::JoystickButton> joystickButton3;
	std::shared_ptr<frc::JoystickButton> joystickButton2;
	std::shared_ptr<frc::JoystickButton> joystickButton1;

//	bool SolenoidButton9;
//	bool SolenoidButton10;
//	bool SolenoidButton11;
//	bool SolenoidButton12;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	//std::shared_ptr<frc::Joystick> getJoystick1();
	std::shared_ptr<frc::XboxController> getXbox1();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
